### ISSUE TITLE
Dashboard (Basic Facelift) 

### ISSUE THREAD

**Issue by LebToki** [ochoarobert1/ccontrol#9]
can be expanded further

	public function ccontrol_dashboard() {
			// Prepare data for dashboard widgets
			$totalClients = $this->ccontrol_total_clients();
			$totalQuotes = $this->ccontrol_total_quotes();
			$totalInvoices = $this->ccontrol_total_invoices();
			
			// Dashboard title and description
			$pluginDirUrl = esc_url(plugin_dir_url(dirname(__FILE__, 2)) . 'ccontrol/assets/images/icon_contacts.png');
			$adminPageTitle = esc_html(get_admin_page_title());
			$clientsIconUrl = esc_url(plugin_dir_url(dirname(__FILE__, 2)) . 'ccontrol/assets/images/icon_contacts.png');
			// Combined HTML output
			$html = <<<HTML
    <div class="wrap">
        <div style="display: flex; align-items: center; justify-content: start; gap: 20px; margin-bottom: 20px;">
            
            <div>
                <img src="{$pluginDirUrl}" alt="Contacts Icon" style="width: 64px;">
            </div>
            
            
            <div>
                <h1>{$adminPageTitle}
                    <br>
                    <small style="font-size: 12px; color: darkgray; display: block">
                        Manage your Business Operations with Ease
                    </small>
                </h1>
            </div>
        </div>
        <style>
        .dashboard-widgets {
        display: flex;
        gap: 20px;
    }

    .dashboard-widget {
        background: #fff;
        border: 1px solid #ddd;
        padding: 20px;
        width: calc(33.333% - 20px);
        box-shadow: 0 1px 3px rgba(0,0,0,.2);
            --bs-card-spacer-y: 1.5rem;
    --bs-card-spacer-x: 1.5rem;
    }
    
.w-100 {
    width: 100% !important;
}

</style>
<div class="min-height-300 bg-primary position-absolute w-100"></div>
        <div class="dashboard-widgets">
            <div class="dashboard-widget">
                <h2>Total Clients</h2>
                <p style="font-size: 1.625rem; font-weight: 500;">{$totalClients}</p>
            </div>
            <div class="dashboard-widget">
                <h2>Total Quotations</h2>
                <p style="font-size: 1.625rem;font-weight:500;">{$totalQuotes}</p>
            </div>
            <div class="dashboard-widget">
                <h2>Total Invoices</h2>
                <p style="font-size: 1.625rem;font-weight:500;">{$totalInvoices}</p>
            </div>
            
            
    </div>
HTML;
			
			echo $html;
		}

**Comment by LebToki** [comment]
![Dashboard](https://github.com/ochoarobert1/ccontrol/assets/957618/00c76d48-1ff4-499c-9c72-63bf8fc9a4f1)
This is a very basic facelist and can be expanded further based on your needs

**Comment by ochoarobert1** [comment]
Thanks a lot man! 
At least with this, i can have a facelift of this section.
I've put the logo I added via plugin options in the next release.
